#!/bin/bash

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

id_for_container(){
  CONTAINER="$1\s*$"
  CONTAINER_ID="$(docker ps -a | grep "$CONTAINER" | awk '{print $1}')"
  echo $CONTAINER_ID
}

if [ ! -z "$(id_for_container 'pomodoro-ws-test')" ]; then
  docker rm -f pomodoro-ws-test
fi

docker run -it \
  --name pomodoro-ws-test \
  --env MIX_ENV="test" \
  -v $PROJECT_DIR/ws:/usr/src/app \
  christianfei/pomodoro-ws sh -c 'mix do clean, deps.get, compile, test'

TEST_RESULT_CODE=$?

exit $TEST_RESULT_CODE
