#!/bin/sh

echo "--> installing global dependencies\n\n\n"
npm install

echo "--> installing app dependencies\n\n\n"
(cd app; npm install; NODE_PATH=node_modules ./node_modules/gulp/bin/gulp.js)

echo "--> installing api dependencies\n\n\n"
(cd api; npm install)

echo "--> creating credentials.json"
cp credentials.template.json credentials.json

echo "--> creating opt/docker.env"
cp opt/docker.template.env opt/docker.env

echo "--> setting up self-signed certificate"
unzip ssl.zip -d .
