#!/bin/bash

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(dirname $SCRIPT_DIR)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

ENV="PRO"
if [ "$1" = "DEV" ];then
  ENV="DEV"
fi

echo "\n\n\n"
echo "=============================="
echo "sourcing environment variables"
echo "=============================="
source $PROJECT_DIR/opt/docker.env

echo "\n\n\n"
echo "========="
echo "|ENV=$ENV|"
echo "========="

id_for_container(){
  CONTAINER="$1\s*$"
  CONTAINER_ID="$(docker ps -a | grep "$CONTAINER" | awk '{print $1}')"
  echo $CONTAINER_ID
}







if [ -z "$(id_for_container 'pomodoro-api-sessions')" ]; then
  echo "\n\n"
  echo "----> STARTING 'pomodoro-api-sessions'"
  docker run --name pomodoro-api-sessions \
    --restart=always \
    --detach=true \
    redis:latest \
    redis-server
fi




if [ -z "$(id_for_container 'pomodoro-api-db')" ]; then
  echo "\n\n"
  echo "----> STARTING 'pomodoro-api-db'"
  docker run --name pomodoro-api-db \
    --restart=always \
    --detach=true \
    --volume /db:/data/db \
    --volume /backup:/backup \
    mongo:latest
fi





if [ -z "$(id_for_container 'pomodoro-blog')" ]; then
  echo "\n\n"
  echo "----> STARTING 'pomodoro-blog'"
  docker run --name pomodoro-blog \
    --restart=always \
    --detach=true \
    --volume $PROJECT_DIR/blog:/srv/jekyll \
    jekyll/stable \
    jekyll s
fi





if [ -z "$(id_for_container 'pomodoro-api')" ]; then
  echo "\n\n"
  echo "----> STARTING 'pomodoro-api'"
  docker run --name pomodoro-api \
    --restart=always \
    --detach=true \
    --env ENV="$ENV" \
    --volume $PROJECT_DIR/credentials.json:/credentials.json \
    --volume $PROJECT_DIR/shared:/shared \
    --link pomodoro-api-sessions:pomodoro-api-sessions \
    --link pomodoro-api-db:pomodoro-api-db \
    christianfei/pomodoro-api
fi





if [ -z "$(id_for_container 'pomodoro-app')" ]; then
  echo "\n\n"
  echo "----> STARTING 'pomodoro-app'"
  VOLUME=""
  if [ "$ENV" = "DEV" ]; then
    VOLUME="--volume $PROJECT_DIR/app/www:/var/www/pomodoro.cc/"
  fi
  docker run --name pomodoro-app \
    --restart=always \
    --detach=true \
    --env PRERENDER_TOKEN="$PRERENDER_TOKEN" \
    $VOLUME \
    christianfei/pomodoro-app
fi





if [ -z "$(id_for_container 'pomodoro-main')" ]; then
  echo "\n\n"
  echo "----> STARTING 'pomodoro-main'"
  docker run --name pomodoro-main \
    --restart=always \
    --detach=true \
    --publish 80:80 \
    --publish 443:443 \
    --link pomodoro-app:pomodoro-app \
    --link pomodoro-api:pomodoro-api \
    --link pomodoro-blog:pomodoro-blog \
    --volume $PROJECT_DIR/main/etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
    --volume $PROJECT_DIR/ssl:/etc/nginx/ssl/pomodoro.cc \
    nginx:1.9.1
fi




echo "\n\n\n"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMNmMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMNMMMMMMMMMmoyyNMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMNshhddmNMMdyhyMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMmddyyhhhhysoyh+yhhdhhdhhmMMMMMMMMMMMMM"
echo "MMMMMMMMNhyoooo+sydysyhhhhhhhhhhhsso/+oydMMMMMMMMM"
echo "MMMMMMNyoooooooooyyhhhhshhyyhhhsom++oooooohMMMMMMM"
echo "MMMMMmooooooo+o+shhhhhyshhh/yyhhhys/o+ooooooNMMMMM"
echo "MMMMd+oooooo+syyyyyyyhNhhhhsmyohhdhyo+ooooooomMMMM"
echo "MMMN+ooooooooooooyso+o/hyhhsy/o++oo+ooooooososMMMM"
echo "MMMsooooooooooooooooooo+-shohoooooooooooooooo+MMMM"
echo "MMM/oooooooooooooooooooo++sy+oooooooooooooooo+NMMM"
echo "MMM/ooooooooooooooooooooooooooooooooooooooooooyMMM"
echo "MMMooooooooooooooooooooooooooooooooooooooooooomMMM"
echo "MMMyooooooooooooooooooooooooooooooooooooooooo+NMMM"
echo "MMMMooooooooooooooooooooooooooooooooooooooooosMMMM"
echo "MMMMd+oooooooooooooooooooooooooooooooooooooooNMMMM"
echo "MMMMMyoooooooooooooooooooooooooooooooooooooomMMMMM"
echo "MMMMMMNooooooooooooooooooooooooooooooooooooNMMMMMM"
echo "MMMMMMMMdoooooooooooooooooooooooooooooooohMMMMMMMM"
echo "MMMMMMMMMMdooooooooooooooooooooooooooosdMMMMMMMMMM"
echo "MMMMMMMMMMMMdho+oooooooooooooooooo+shNMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMNdhysooo+ooosossyhdMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
